source 'https://supermarket.chef.io'

metadata

cookbook 'delivery-truck', github: 'chef-cookbooks/delivery-truck'
cookbook 'delivery-sugar', github: 'chef-cookbooks/delivery-sugar'
cookbook 'gpg', git: 'https://github.com/sous-chefs/gpg', ref: '2f682a1406047e99351d184fe18fff035a0c856c'

group :delivery do
  cookbook 'test', path: './test/fixtures/cookbooks/test'
end
